export const textStyles = {
  'h3-semibold': {
    fontWeight: 600,
    lineHeight: '2.25rem',
    fontSize: '1.75rem',
    letterSpacing: '-0.019em',
    fontFamily: 'body',
  },
  banner: {
    fontSize: '1.25rem',
    fontStyle: 'normal',
    fontFamily: 'Inter',
    fontWeight: '600',
    lineHeight: '1.75rem',
    letterSpacing: '-0.28px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  noteView: {
    fontSize: '0.875rem',
    fontStyle: 'normal',
    fontFamily: 'Inter',
    fontWeight: '400',
    lineHeight: '1.25rem',
    letterSpacing: '-0.084px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
}
